### ISSUE TITLE
Не могу скачать библиотеку

### ISSUE THREAD

**Issue by flaxytop** [Mih4n/spworlds-csharp-library#1]
IDE Visual Studio, Ошибка: Не удалось установить пакет «spworlds». Вы пытаетесь установить этот пакет в проект, требуемая версия платформы которого — «.NETFramework,Version=v4.7.2», но в пакете нет ссылок на сборки или файлов содержимого, совместимых с этой платформой. Дополнительную информацию можно получить у автора пакета.

**Comment by Mih4n** [comment]
Вы скорее всего используете отличный от .net7 framework. Было проверено и данная библиотека работает .net6 .net7 точно.

**Comment by flaxytop** [comment]
все разобрался спасибо
